keys:
    - &noa age10rmq9vcjjpxpl7qx2qc9nh6xvr0ktdjphq7w6mz9zwlz6kxxfprqfrz7gk
    - &host_zinnia age1c74akxues9dluu7pzu3m0ne9n7tve05yxkxauadgdkpwp9cr2pusctujau
    - &host_seralia age1vfnd3vq40q5kvh68ftwyh6wxfkf5906xejt4689nvrq99vrslprqtpumg7
    - &host_ivy age13wmpnkt79dzzg9t74w9xmvzwsnyx7mfkakzkz9n4dya469wvqshq5rpevv
    - &host_mimosa age1garpt27lnsj4mjvnm7ytszwmzl4e845y554z3k2308sngkzzm4yqadyyp2
    - &host_darwin_oryx age1e2488lstgy5dgj65qs7l7mxqwzrk7wgnpsmga8e9h98r8ts6cv7qltt940
    - &host_darwin_fervorine age16vr5ht3m3yfauj7k0sgr9n4dzd0mslxfhs0q8de3766mzsmsw9yq5s37fl
creation_rules:
    - path_regex: secrets/home.yaml$
      key_groups:
          - age:
                - *noa
                - *host_zinnia
    - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
      key_groups:
          - age:
                - *noa
                - *host_zinnia
                - *host_seralia
                - *host_ivy
                - *host_mimosa
                - *host_darwin_oryx
                - *host_darwin_fervorine
