format = """
$username\
$hostname\
$directory\
$direnv\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$fill\
$env_var\
$line_break\
$python\
$character"""

[fill]
symbol = ' '

[directory]
style = "blue"
read_only = " 󰌾"

[character]
success_symbol = "[](purple)"
error_symbol = "[](red)"
vimcmd_symbol = "[](green)"

[git_branch]
format = "[$branch]($style) "
style = "bright-black"

[git_status]
format = "[($conflicted$untracked$modified$staged$renamed$deleted$ahead_behind$stashed)](yellow) "
conflicted = "="
untracked = "?"
modified = "*"
staged = "+"
renamed = "r"
deleted = "d"
stashed = "\\$"
ahead = ""
behind = ""

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\)'
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[python]
format = "[$virtualenv]($style) "
style = "bright-black"

[env_var.ANY_NIX_SHELL_PKGS]
format = "with[$env_value]($style) "
style = "bright-black dimmed"
