name: Irrigation

on:
  workflow_dispatch:
    inputs:
      name:
        type: string
        description: Which machine to deploy
        required: true

jobs:
  deploy:
    name: Deploy system to ${{ inputs.name }}
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
        with:
          path: "flake"

      - name: Add SSH known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -v -T 30 -H ${{ inputs.name }} >> ~/.ssh/known_hosts

      - name: Extract secrets.rev from flake.lock
        id: extract-secrets-rev
        working-directory: ./flake
        run: |
          rev=$(jq -r '.nodes.secrets.locked.rev' flake.lock)
          echo "rev=$rev" >> $GITHUB_OUTPUT

      - name: Checkout secrets
        uses: actions/checkout@v4
        with:
          repository: "AsterisMono/secrets"
          ref: ${{ steps.extract-secrets-rev.outputs.rev }}
          token: ${{ secrets.SECRETS_PAT }}
          path: "secrets"

      - name: Deploy
        working-directory: ./flake
        run: |
          nix run nixpkgs#nixos-rebuild -- \
            --flake .#${{ inputs.name }} \
            --target-host root@${{ inputs.name }} \
            switch \
            --override-input secrets ../secrets
