name: System Deployment

on:
  workflow_dispatch:
    inputs:
      name:
        type: string
        description: Which machine to deploy
        required: true

jobs:
  prepare:
    uses: AsterisMono/flake/.github/workflows/prepare.yml@main
    secrets:
      SECRETS_PAT: ${{ secrets.SECRETS_PAT }}

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci

      - name: Run flake check
        working-directory: ./flake
        run: nix flake check . --override-input secrets ../secrets
