# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      name:
        type: string
        description: Which machine to deploy
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          path: "flake"

      - name: Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci

      - name: Install Nix
        uses: cachix/install-nix-action@v31.1.0

      - name: Extract secrets.rev from flake.lock
        id: extract-secrets-rev
        working-directory: ./flake
        run: |
          rev=$(jq -r '.nodes.secrets.locked.rev' flake.lock)
          echo "rev=$rev" >> $GITHUB_OUTPUT

      - name: Checkout secrets
        uses: actions/checkout@v4
        with:
          repository: "AsterisMono/secrets"
          ref: ${{ steps.extract-secrets-rev.outputs.rev }}
          token: ${{ secrets.SECRETS_PAT }}
          path: "secrets"

      - name: Run flake check
        working-directory: ./flake
        run: nix flake check . --override-input secrets ../secrets
