name: Prepare flake

on:
  workflow_call:
    secrets:
      SECRETS_PAT:
        required: true

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: "flake"

      - name: Install Nix
        uses: cachix/install-nix-action@v31.1.0

      - name: Extract secrets.rev from flake.lock
        id: extract-secrets-rev
        working-directory: ./flake
        run: |
          rev=$(jq -r '.nodes.secrets.locked.rev' flake.lock)
          echo "rev=$rev" >> $GITHUB_OUTPUT

      - name: Checkout secrets
        uses: actions/checkout@v4
        with:
          repository: "AsterisMono/secrets"
          ref: ${{ steps.extract-secrets-rev.outputs.rev }}
          token: ${{ secrets.SECRETS_PAT }}
          path: "secrets"